wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.2757529540797966
hidden_size_1:
  value: 128
hidden_size_2:
  value: 64
hidden_size_3:
  value: 32
learning_rate:
  value: 0.002933966402915868
