wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.3302059057410263
hidden_size_1:
  value: 512
hidden_size_2:
  value: 64
hidden_size_3:
  value: 32
learning_rate:
  value: 0.007889958721903251
