wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.3600423803953462
hidden_size_1:
  value: 256
hidden_size_2:
  value: 64
hidden_size_3:
  value: 32
learning_rate:
  value: 0.0016405828852906162
