wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.34122288077850715
hidden_size_1:
  value: 512
hidden_size_2:
  value: 128
hidden_size_3:
  value: 128
learning_rate:
  value: 0.006836785707283214
