wandb_version: 1

batch_size:
  value: 128
dropout_rate:
  value: 0.3098027803196194
hidden_size_1:
  value: 128
hidden_size_2:
  value: 64
hidden_size_3:
  value: 64
learning_rate:
  value: 0.0012579319007443304
