wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.4722957003355611
hidden_size_1:
  value: 256
hidden_size_2:
  value: 256
hidden_size_3:
  value: 128
learning_rate:
  value: 0.007458953076297823
