wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.28775455526868055
hidden_size_1:
  value: 512
hidden_size_2:
  value: 128
hidden_size_3:
  value: 32
learning_rate:
  value: 0.001290853629940954
