wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.20303375939671264
hidden_size_1:
  value: 512
hidden_size_2:
  value: 64
hidden_size_3:
  value: 128
learning_rate:
  value: 0.005838511014918186
