wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.4126498299650587
hidden_size_1:
  value: 128
hidden_size_2:
  value: 64
hidden_size_3:
  value: 64
learning_rate:
  value: 0.002296627030668779
