wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.35277011577553785
hidden_size_1:
  value: 128
hidden_size_2:
  value: 128
hidden_size_3:
  value: 32
learning_rate:
  value: 0.0036612455206969977
