wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.4736551053034015
hidden_size_1:
  value: 128
hidden_size_2:
  value: 64
hidden_size_3:
  value: 64
learning_rate:
  value: 0.007817888289870031
