wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.39347678233628713
hidden_size_1:
  value: 256
hidden_size_2:
  value: 128
hidden_size_3:
  value: 32
learning_rate:
  value: 0.008891968692417252
