wandb_version: 1

batch_size:
  value: 128
dropout_rate:
  value: 0.13299372259756215
hidden_size_1:
  value: 128
hidden_size_2:
  value: 256
hidden_size_3:
  value: 32
learning_rate:
  value: 0.008041621412916027
