wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.2371081605927848
hidden_size_1:
  value: 512
hidden_size_2:
  value: 128
hidden_size_3:
  value: 64
learning_rate:
  value: 0.008171519565005217
