wandb_version: 1

batch_size:
  value: 128
dropout_rate:
  value: 0.3031807006803935
hidden_size_1:
  value: 256
hidden_size_2:
  value: 64
hidden_size_3:
  value: 64
learning_rate:
  value: 0.0027718483227793947
