wandb_version: 1

batch_size:
  value: 32
dropout_rate:
  value: 0.11104453018148425
hidden_size_1:
  value: 256
hidden_size_2:
  value: 128
hidden_size_3:
  value: 64
learning_rate:
  value: 0.002312384422606596
