wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.3917641365421102
hidden_size_1:
  value: 1024
hidden_size_2:
  value: 512
hidden_size_3:
  value: 256
learning_rate:
  value: 0.003625189252097043
