_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 23
                - 55
                - 62
            "4": 3.11.4
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 64
dropout_rate:
    value: 0.2757529540797966
hidden_size_1:
    value: 128
hidden_size_2:
    value: 64
hidden_size_3:
    value: 32
learning_rate:
    value: 0.002933966402915868
